### ISSUE TITLE
time type error  in mybatis log  console

### ISSUE THREAD

**Issue by bald-head** [mbtsp/mybatisSmartCodeHelp#14]
![image](https://github.com/mbtsp/mybatisSmartCodeHelp/assets/62256948/83d37ce5-20b4-4213-bdf8-b2e18739322c)

**Comment by bald-head** [comment]
@zoulejiu

**Comment by zoulejiu** [comment]
Thanks, checking

**Comment by zoulejiu** [comment]
fix 2023.1.1
