### ISSUE TITLE
选择mybatis sql日志转成sql并执行  多了个button

### ISSUE THREAD

**Issue by soaped** [mbtsp/mybatisSmartCodeHelp#3]
![F95E4C71853CB78D5A6722F1DE94E9A5](https://user-images.githubusercontent.com/22208734/196647431-0ad1a648-5bf2-496b-9eb8-74845fdb91b2.jpg)

这两个按钮跳转的地方一样

**Comment by zoulejiu** [comment]
2022.3.3版本已修复
